### PR TITLE
fixes revision access to users with view revision access

### LINKED ISSUE #6: normal user with revision permission doesn't have access
Other user that user/1 don't have access to the revision tab even with the revision permission. However, disabling diff module get thinks to normal again and revisions tab is there again.

### PR DESCRIPTION
**Pull request by robertgarrigos**
it fixes #6

### CODE REVIEW

**Comment by Graham-72** [comment]
@robertgarrigos I think there is more needed to fix this issue and it seems the porting is incomplete or incorrect. I am going to investigate what else needs doing.

**Review by Graham-72 — CHANGES_REQUESTED** [review]
I think there is another error, in the line
`return $may_revision_this_type && _node_revision_access($node, $op);`
There is no such function as `_node_revision_access`. This error is inherited from the D7 version.
I believe the line should be 
`return $may_revision_this_type;`

**Comment by robertgarrigos** [comment]
in fact, there is: https://api.backdropcms.org/api/backdrop/core%21modules%21node%21node.module/function/_node_revision_access/1

**Comment by Graham-72** [comment]
Yes, my mistake. I was misled by the function name beginning with an underscore `(_node_revision_access)` which does not conform to our naming convention. Now I am wondering about the purpose of using this function here in diff module. 
I am in the process of preparing another PR that will make a change to `function diff_node_revision_access` because of sorting out the config settings references. I think adding some comments in here might also be helpful, to explain what the function is doing.

**Pull request merged**
